SPEED_OF_LIGHT = 3* 10**8
SECONDS_PER_MIN = 60
MIN_PER_HR = 60
HRS_PER_DAY = 24
DAYS_PER_YR = 365

METERS_PER_YR = SPEED_OF_LIGHT * SECONDS_PER_MIN * MIN_PER_HR * HRS_PER_DAY * DAYS_PER_YR

print("The value of a light-year is: ", METERS_PER_YR, "meters.")
